spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: game
      option:
        max-connection-per-host: 1000
        min-connection-per-host: 50

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
